#pragma once

#define CONFIG_ENABLE_CLIPRECT   1
#define CONFIG_ENABLE_OFFSET     1
#define CONFIG_ENABLE_SCALE_POS  1
#define CONFIG_ENABLE_SCALE_SIZE 1

#define CONFIG_ENABLE_CIRCLE 1
#define CONFIG_ENABLE_STRING 1
#define CONFIG_ENABLE_IMAGE  1

#define CONFIG_USE_DOUBLE_PRECISION_FLOATS 0
